version: "3"
services:
  login-automatico-admin:
    image: ${IMG_FULLNAME}
    logging:
      driver: "json-file"
      options:
        max-size: "900k"
        max-file: "3"
    ports:
      - "8090:9090"
    volumes:
      - ./config:/login-automatico-admin/config
      - ./logs:/login-automatico-admin/logs
    networks:
      - login-automatico-admin-net
networks:
  login-automatico-admin-net:
